apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-echo
  labels:
    app: svc-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-echo
  template:
    metadata:
      labels:
        app: svc-echo
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "verify"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "debug"
#        dapr.io/config: "tracing"
    spec:
      containers:
        - name: server
          image: davidleitw/dapr-test-svc-echo:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: svc-echo
  labels:
    app: svc-echo
spec:
  selector:
    app: svc-echo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer